// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyCWoFQkfH6S5qvmZBPfOZi--12Ml5KoY',
    appId: '1:256824865171:web:f247c860731d8f2cd63866',
    messagingSenderId: '256824865171',
    projectId: 'thread-practice',
    authDomain: 'thread-practice.firebaseapp.com',
    storageBucket: 'thread-practice.appspot.com',
    measurementId: 'G-X6E34R5RCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6gJ1sa590QeysHfPR4hBZ-uljwaL914g',
    appId: '1:256824865171:android:82169f8a0965ce07d63866',
    messagingSenderId: '256824865171',
    projectId: 'thread-practice',
    storageBucket: 'thread-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMTU8EFHBVFhhAKaP4mtHH9Ml7J0hBz-k',
    appId: '1:256824865171:ios:23101bb052f96dfdd63866',
    messagingSenderId: '256824865171',
    projectId: 'thread-practice',
    storageBucket: 'thread-practice.appspot.com',
    iosBundleId: 'com.example.threadClone',
  );
}
